# Generated by Django 6.0.4 on 2026-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='GitHub repository URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_project_link',
            field=models.URLField(blank=True, help_text='Live project URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_documentation',
            field=models.TextField(blank=True, help_text='Project documentation and notes'),
        ),
    ]
