# Generated by Django 6.0.4 on 2026-05-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_project_github_link_project_live_project_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_documentation',
            field=models.FileField(blank=True, help_text='Project documentation PDF', null=True, upload_to='project_docs/'),
        ),
    ]
