# Generated by Django 6.0.4 on 2026-05-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_alter_project_project_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_deliverable',
            field=models.FileField(blank=True, help_text='Task deliverable PDF', null=True, upload_to='task_deliverables/'),
        ),
    ]
